//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLO365.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CLO365.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cancel {
            get {
                object obj = ResourceManager.GetObject("cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap checked__1_ {
            get {
                object obj = ResourceManager.GetObject("checked__1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cloud_computing {
            get {
                object obj = ResourceManager.GetObject("cloud_computing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cloud_computing__1_ {
            get {
                object obj = ResourceManager.GetObject("cloud_computing__1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cloud_computing__3_ {
            get {
                object obj = ResourceManager.GetObject("cloud_computing__3_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cloud_computing__4_ {
            get {
                object obj = ResourceManager.GetObject("cloud_computing__4_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap computer_1_ {
            get {
                object obj = ResourceManager.GetObject("computer_1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap contract {
            get {
                object obj = ResourceManager.GetObject("contract", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap down_arrow {
            get {
                object obj = ResourceManager.GetObject("down_arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit {
            get {
                object obj = ResourceManager.GetObject("edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit_1_ {
            get {
                object obj = ResourceManager.GetObject("edit_1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file {
            get {
                object obj = ResourceManager.GetObject("file", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder {
            get {
                object obj = ResourceManager.GetObject("folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_1_ {
            get {
                object obj = ResourceManager.GetObject("folder_1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a valid 2fa code that you might have received on your authentication app registered for GitHub..
        /// </summary>
        internal static string LabelMsgEnterOTP {
            get {
                return ResourceManager.GetString("LabelMsgEnterOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, You do not have permission to access files. Please contact your network administrator..
        /// </summary>
        internal static string MsgAccessDenied {
            get {
                return ResourceManager.GetString("MsgAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please accept/reject all pending changes to proceed..
        /// </summary>
        internal static string MsgAllItemsNotReviwed {
            get {
                return ResourceManager.GetString("MsgAllItemsNotReviwed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Asset has been added successfully to the playlist: {0}.
        /// </summary>
        internal static string MsgAssetAddedSuccessfully {
            get {
                return ResourceManager.GetString("MsgAssetAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected Asset &quot;{0}&quot; has been removed successfully..
        /// </summary>
        internal static string MsgAssetDeletionSuccessfull {
            get {
                return ResourceManager.GetString("MsgAssetDeletionSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected Asset &quot;{0}&quot; has been updated successfully..
        /// </summary>
        internal static string MsgAssetUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("MsgAssetUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Role metadata added successfully..
        /// </summary>
        internal static string MsgAudienceAddedSuccessfully {
            get {
                return ResourceManager.GetString("MsgAudienceAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role details are updated successfully..
        /// </summary>
        internal static string MsgAudienceUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("MsgAudienceUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The updated CLO365 content JSON files have been uploaded to GitHub repository by .
        /// </summary>
        internal static string MsgAutoCommitMsg {
            get {
                return ResourceManager.GetString("MsgAutoCommitMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Category metadata added successfully..
        /// </summary>
        internal static string MsgCategoryAddedSuccessfully {
            get {
                return ResourceManager.GetString("MsgCategoryAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category details are updated successfully..
        /// </summary>
        internal static string MsgCategoryUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("MsgCategoryUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The changes you have made have not been saved yet.
        ///Click &apos;Yes&apos; to save the changes or &apos;No&apos; to discard the changes before proceeding..
        /// </summary>
        internal static string MsgChangesNotSaved {
            get {
                return ResourceManager.GetString("MsgChangesNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, There is nothing to commit..
        /// </summary>
        internal static string MsgCommitFailed {
            get {
                return ResourceManager.GetString("MsgCommitFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before uploading/committing the changes to GitHub staging repository as a newer version, please provide a short message to describe the changes you have done in this version..
        /// </summary>
        internal static string MsgCommitMsgCannotbeEmpty {
            get {
                return ResourceManager.GetString("MsgCommitMsgCannotbeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The updated CLO365 content JSON files have been uploaded to GitHub staging repository..
        /// </summary>
        internal static string MsgCommitSuccess {
            get {
                return ResourceManager.GetString("MsgCommitSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure, you want to cancel your changes?.
        /// </summary>
        internal static string MsgConfirmCancelClick {
            get {
                return ResourceManager.GetString("MsgConfirmCancelClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to change this unique Id (GUID)? 
        ///
        ///Note: Playlist GUIDs are used/referenced by the SharePoint app, so it is advised not to change the ID of any existing playlist. .
        /// </summary>
        internal static string MsgConfirmChangeGuid {
            get {
                return ResourceManager.GetString("MsgConfirmChangeGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to exit without setting up the CLO365 repository locally?.
        /// </summary>
        internal static string MsgConfirmCloseCloneForm {
            get {
                return ResourceManager.GetString("MsgConfirmCloseCloneForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete the selected item?.
        /// </summary>
        internal static string MsgConfirmDelete {
            get {
                return ResourceManager.GetString("MsgConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish to production requires latest files to be downloaded and merged to continue. Click Yes to proceed or No to cancel the operation..
        /// </summary>
        internal static string MsgConfirmPullonPushtoProd {
            get {
                return ResourceManager.GetString("MsgConfirmPullonPushtoProd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are some merge issue in uploading the files to staging repo. Do you want to download the latest and merge your changes to it?.
        /// </summary>
        internal static string MsgConfirmToPullonMergeException {
            get {
                return ResourceManager.GetString("MsgConfirmToPullonMergeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill description. (Required field)..
        /// </summary>
        internal static string MsgDescCannotbeEmpty {
            get {
                return ResourceManager.GetString("MsgDescCannotbeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  have some special characters found in the changes and that is causing some conflict during the merge. Please remove the special characters..
        /// </summary>
        internal static string MsgFilesContainsMergeConflict {
            get {
                return ResourceManager.GetString("MsgFilesContainsMergeConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some unexpected error occured, please try again..
        /// </summary>
        internal static string MsgGenericError {
            get {
                return ResourceManager.GetString("MsgGenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a valid unique Id..
        /// </summary>
        internal static string MsgIdCannotbeEmpty {
            get {
                return ResourceManager.GetString("MsgIdCannotbeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id exists already. Please enter a valid and unique id..
        /// </summary>
        internal static string MsgIdExistsAlready {
            get {
                return ResourceManager.GetString("MsgIdExistsAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide an image file..
        /// </summary>
        internal static string MsgImageCannotbeEmpty {
            get {
                return ResourceManager.GetString("MsgImageCannotbeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimensions of the image file is incorrect. Maximum allowed dimension is 280x200..
        /// </summary>
        internal static string MsgImageFileSizeExceeds {
            get {
                return ResourceManager.GetString("MsgImageFileSizeExceeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The credentials provided are not valid. Please try again with valid GitHub credentials..
        /// </summary>
        internal static string MsgInvalidCredentials {
            get {
                return ResourceManager.GetString("MsgInvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a valid 2fa code that you might have received on your authentication app registered for GitHub..
        /// </summary>
        internal static string MsgInvalidOTP {
            get {
                return ResourceManager.GetString("MsgInvalidOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level metadata has been added successfully..
        /// </summary>
        internal static string MsgLevelAddedSuccessfully {
            get {
                return ResourceManager.GetString("MsgLevelAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level metadata has been updated successfully..
        /// </summary>
        internal static string MsgLevelUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("MsgLevelUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, some network related error occured. Please make sure that you are not using email id for username..
        /// </summary>
        internal static string MsgLoginFailure {
            get {
                return ResourceManager.GetString("MsgLoginFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This metadata is in use and is associated with {0} playlists and {1} assets. Cannot remove the metadata.
        /// </summary>
        internal static string MsgMetadatainUseCannotReject {
            get {
                return ResourceManager.GetString("MsgMetadatainUseCannotReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a name. Name cannot be empty..
        /// </summary>
        internal static string MsgNameCannotbeEmpty {
            get {
                return ResourceManager.GetString("MsgNameCannotbeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given name exists already. Please enter a different name..
        /// </summary>
        internal static string MsgNameExistsAlready {
            get {
                return ResourceManager.GetString("MsgNameExistsAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, some network related error occured. Please try again..
        /// </summary>
        internal static string MsgNetworkError {
            get {
                return ResourceManager.GetString("MsgNetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a valid 2fa code..
        /// </summary>
        internal static string MsgOTPCannotbeEmpty {
            get {
                return ResourceManager.GetString("MsgOTPCannotbeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide password. It cannot be empty..
        /// </summary>
        internal static string MsgPasswordCannotbeEmpty {
            get {
                return ResourceManager.GetString("MsgPasswordCannotbeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Playlist has been added successfully.
        /// </summary>
        internal static string MsgPlaylistAddedSuccessfully {
            get {
                return ResourceManager.GetString("MsgPlaylistAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected Playlist &quot;{0}&quot; has been removed successfully..
        /// </summary>
        internal static string MsgPlaylistDeletionSuccessfull {
            get {
                return ResourceManager.GetString("MsgPlaylistDeletionSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected Playlist &quot;{0}&quot; has been updated successfully..
        /// </summary>
        internal static string MsgPlaylistUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("MsgPlaylistUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use your username (do not use email address).
        /// </summary>
        internal static string MsgProvideUsernameNotEmail {
            get {
                return ResourceManager.GetString("MsgProvideUsernameNotEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CLO365 content files has been successfully downloded from GitHub staging repository to the local folder.
        /// </summary>
        internal static string MsgPullFilesSuccess {
            get {
                return ResourceManager.GetString("MsgPullFilesSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are some merge issue in uploading the files to staging repo. Please follow the following steps to resolve this issue:
        ///1. Backup your files
        ///2. Pull files from repository
        ///3. Compare files and resolve conflicts
        ///4. Push files to repository.
        /// </summary>
        internal static string MsgPushConflictOccured {
            get {
                return ResourceManager.GetString("MsgPushConflictOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes to the content files have been uploaded to GitHub repo successfully..
        /// </summary>
        internal static string MsgPushedSuccessfully {
            get {
                return ResourceManager.GetString("MsgPushedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes to the content files have been uploaded to GitHub production repo successfully..
        /// </summary>
        internal static string MsgPushedtoProductionSuccessfully {
            get {
                return ResourceManager.GetString("MsgPushedtoProductionSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide the security information..
        /// </summary>
        internal static string MsgSecurityCannotbeEmpty {
            get {
                return ResourceManager.GetString("MsgSecurityCannotbeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please browse and select a local folder. This folder will be used to download/clone the files from GitHub Staging repository to it..
        /// </summary>
        internal static string MsgSelectFoldertoClone {
            get {
                return ResourceManager.GetString("MsgSelectFoldertoClone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source metadata added successfully..
        /// </summary>
        internal static string MsgSourceAddedSuccessfully {
            get {
                return ResourceManager.GetString("MsgSourceAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source metadata updated successfully..
        /// </summary>
        internal static string MsgSourceUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("MsgSourceUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubCategory metadata added successfully..
        /// </summary>
        internal static string MsgSubCategoryAddedSuccessfully {
            get {
                return ResourceManager.GetString("MsgSubCategoryAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubCategory metadata updated successfully..
        /// </summary>
        internal static string MsgSubCategoryUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("MsgSubCategoryUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject metdata added successfully..
        /// </summary>
        internal static string MsgSubjectAddedSuccessfully {
            get {
                return ResourceManager.GetString("MsgSubjectAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject metdata updated successfully..
        /// </summary>
        internal static string MsgSubjectUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("MsgSubjectUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technology metdata added successfully..
        /// </summary>
        internal static string MsgTechAddedSuccessfully {
            get {
                return ResourceManager.GetString("MsgTechAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technology metdata updated successfully..
        /// </summary>
        internal static string MsgTechUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("MsgTechUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide Title. It cannot be empty..
        /// </summary>
        internal static string MsgTitleCannotbeEmpty {
            get {
                return ResourceManager.GetString("MsgTitleCannotbeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide valid URL. It cannot be empty..
        /// </summary>
        internal static string MsgUrlCannotbeEmpty {
            get {
                return ResourceManager.GetString("MsgUrlCannotbeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a valid username..
        /// </summary>
        internal static string MsgUsernameCannotbeEmpty {
            get {
                return ResourceManager.GetString("MsgUsernameCannotbeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap playlist_3_ {
            get {
                object obj = ResourceManager.GetObject("playlist_3_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap refresh {
            get {
                object obj = ResourceManager.GetObject("refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap remove {
            get {
                object obj = ResourceManager.GetObject("remove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap save {
            get {
                object obj = ResourceManager.GetObject("save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap scroll_arrow_to_down {
            get {
                object obj = ResourceManager.GetObject("scroll_arrow_to_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap scroll_arrow_to_down__1_ {
            get {
                object obj = ResourceManager.GetObject("scroll_arrow_to_down__1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap status_1 {
            get {
                object obj = ResourceManager.GetObject("status-1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production.
        /// </summary>
        internal static string StrProductionFolderName {
            get {
                return ResourceManager.GetString("StrProductionFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Select any from the list).
        /// </summary>
        internal static string StrSelectAnyComboOption {
            get {
                return ResourceManager.GetString("StrSelectAnyComboOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staging.
        /// </summary>
        internal static string StrStagingFolderName {
            get {
                return ResourceManager.GetString("StrStagingFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     .
        /// </summary>
        internal static string StrSubjectLevel1Intent {
            get {
                return ResourceManager.GetString("StrSubjectLevel1Intent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to         .
        /// </summary>
        internal static string StrSubjectLevel2Intent {
            get {
                return ResourceManager.GetString("StrSubjectLevel2Intent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to             .
        /// </summary>
        internal static string StrSubjectLevel3Intent {
            get {
                return ResourceManager.GetString("StrSubjectLevel3Intent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap text_document_button_accepted {
            get {
                object obj = ResourceManager.GetObject("text_document_button_accepted", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap text_document_cancel_button {
            get {
                object obj = ResourceManager.GetObject("text_document_cancel_button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes not saved.
        /// </summary>
        internal static string TitleChangesNotSaved {
            get {
                return ResourceManager.GetString("TitleChangesNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm cancel click.
        /// </summary>
        internal static string TitleConfirmCancelClick {
            get {
                return ResourceManager.GetString("TitleConfirmCancelClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm change GUID.
        /// </summary>
        internal static string TitleConfirmChangeGuid {
            get {
                return ResourceManager.GetString("TitleConfirmChangeGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm to close form.
        /// </summary>
        internal static string TitleConfirmCloseCloneForm {
            get {
                return ResourceManager.GetString("TitleConfirmCloseCloneForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm delete.
        /// </summary>
        internal static string TitleConfirmDelete {
            get {
                return ResourceManager.GetString("TitleConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm to pull.
        /// </summary>
        internal static string TitleConfirmPullonPushtoProd {
            get {
                return ResourceManager.GetString("TitleConfirmPullonPushtoProd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm on pull to merge.
        /// </summary>
        internal static string TitleConfirmToPullonMergeException {
            get {
                return ResourceManager.GetString("TitleConfirmToPullonMergeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string TitleError {
            get {
                return ResourceManager.GetString("TitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download and merge files.
        /// </summary>
        internal static string TitlePull {
            get {
                return ResourceManager.GetString("TitlePull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload files.
        /// </summary>
        internal static string TitlePush {
            get {
                return ResourceManager.GetString("TitlePush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string TitleSuccess {
            get {
                return ResourceManager.GetString("TitleSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap up_arrow {
            get {
                object obj = ResourceManager.GetObject("up_arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap up_scroll_arrow {
            get {
                object obj = ResourceManager.GetObject("up_scroll_arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap up_scroll_arrow__1_ {
            get {
                object obj = ResourceManager.GetObject("up_scroll_arrow__1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap writing {
            get {
                object obj = ResourceManager.GetObject("writing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
