define([], function() {
  return {
    "PropertyPaneDescription": "Description",
    "BasicGroupName": "Group Name",
    "DescriptionFieldLabel": "Description Field",
    "ImageSelectorLabel": "Choose an image",
    "ImageSelectorButton":"Choose Image",
    "DetailEditTitle": "Title",
    "DetailEditDescription": "Description",
    "DetailEditUrl": "Url",
    "DetailEditCategory": "Category",
    "DetailEditSubCategory": "Sub Category",
    "DetailEditTechnology": "Technology",
    "DetailEditLevel": "Level",
    "DetailEditAudience": "Audience",
    "AssetSearchPlaceHolderLabel": "Search for Existing Assets",
    "CategoryHeading": "Add new Sub Category",
    "CategoryHeadingLabel": "Sub Category",
    "CategoryPlaylistSavedMessage": "Playlist was saved!",
    "CategoryPlaylistSaveFailedMessage": "Failed to save playlist!",
    "CategoryNewPlayListMessage": "You have made changes to a new playlist. Do you want to discard your changes and continue?",
    "CategoryEditedPlayListMessage": "You have made changes to this playlist. Do you want to discard your changes and continue?",
    "PlaylistEditAssetSavedMessage": "Asset was saved!",
    "PlaylistEditAssetSaveFailedMessage": "Failed to save asset!",
    "PlaylistEditCreatePlaylistHeader": "Create a new playlist",
    "PlaylistEditPlaylistDetailsHeader": "Playlist Details: ",
    "PlaylistEditPlaylistAssetsHeader": "Playlist Assets",
    "PlaylistEditEditLabel": "Edit Detail",
    "PlaylistEditSaveLabel": "Save Detail",
    "PlaylistEditCancelLabel": "Cancel Detail",
    "PlaylistEditCloseLabel": "Close Playlist",
    "AssetEditCreateHeader": "Create a new asset",
    "AssetEditManageHeader": "Manage Custom Asset:",
    "AssetEditDetailsHeader": "Playlist Details: ",
    "AssetEditSaveLabel": "Save Asset",
    "AssetEditCancelLabel": "Cancel Asset",
    "AssetEditOpenPage": "Open Page",
    "TechnologyHeadingLabel": "Technology",
    "SubcategoryHeadingLabel": "Sub Category Heading",
    "PlaylistItemEditPlaylistHeadingLabel": "Playlist",
    "PlaylistItemEditPlaylistDelete": "Delete Playlist",
    "PlaylistEditAssetNewLabel": "New Asset",
    "PlaylistEditAssestExistingLabel": "Existing Asset",
    "PlaylistRemove": "Remove from Playlist",
    "ImageSelectorImageAlt": "Custom Playlist",
    "ImageSelectorUrlPlaceholder" : "Image Url",
    "CategoryHeadingAddPlaylistToSubcategory": "Add new playlist to Sub Category",
    "AdminMenuTechnologyLabel": "Technology",
    "AdminMenuCategoryLabel": "Category",
    "Show": "Show",
    "Hide": "Hide",
    "Add": "Add",
    "Edit": "Edit",
    "CloseButton": "Close",
    "EditButton": "Edit",
    "StepButton": "Step",
    "MoveUpButton": "Move Up",
    "MoveDownButton": "Move Down",
    "SaveButton": "Save",
    "CancelButton": "Cancel",
    "UpdateButton": "Update",
    "DeleteButton": "Delete",
    "DetailEditNewPageMessage": "New asset page in Site Pages library.",
    "DetailEditExistingPageMessage": "Enter the URL of an existing page.",
    "DetailEditNewPageButton": "Create Asset Page",
    "DetailEditExistingPageButton": "Enter Url",
    "NoSearchResults": "No search results matched your query."
  }
});