declare interface ICustomLearningAdminWebPartStrings {
  PropertyPaneDescription: string;
  BasicGroupName: string;
  DescriptionFieldLabel: string;
  ImageSelectorLabel: string;
  ImageSelecterButton: string;
  DetailEditTitle: string;
  DetailEditDescription: string;
  DetailEditUrl: string;
  DetailEditCategory: string;
  DetailEditSubCategory: string;
  DetailEditTechnology: string;
  DetailEditLevel: string;
  DetailEditAudience: string;
  AssetSearchPlaceHolderLabel: string;
  CategoryHeading: string;
  CategoryHeadingLabel: string;
  CategoryPlaylistSavedMessage: string;
  CategoryPlaylistSaveFailedMessage: string;
  CategoryNewPlayListMessage: string;
  CategoryEditedPlayListMessage: string;
  PlaylistEditAssetSavedMessage: string;
  PlaylistEditAssetSaveFailedMessage: string;
  PlaylistEditCreatePlaylistHeader: string;
  PlaylistEditPlaylistDetailsHeader: string;
  PlaylistEditPlaylistAssetsHeader: string;
  PlaylistEditEditLabel: string;
  PlaylistEditSaveLabel: string;
  PlaylistEditCancelLabel: string;
  PlaylistEditCloseLabel: string;
  PlaylistItemEditPlaylistHeadingLabel: string;
  PlaylistItemEditPlaylistDelete: string;
  AssetEditCreateHeader: string;
  AssetEditManageHeader: string;
  AssetEditDetailsHeader: string;
  AssetEditSaveLabel: string;
  AssetEditCancelLabel: string;
  AssetEditOpenPage: string;
  PlaylistEditAssetNewLabel: string;
  PlaylistEditAssestExistingLabel: string;
  Show: string;
  Hide: string;
  Add: string;
  Edit: string;
  CloseButton: string;
  EditButton: string;
  StepButton: string;
  MoveUpButton: string;
  MoveDownButton: string;
  PlaylistRemove: string;
  TechnologyHeadingLabel: string;
  SubcategoryHeadingLabel: string;
  ImageSelectorImageAlt: string;
  ImageSelectorUrlPlaceholder: string;
  SaveButton: string;
  CancelButton: string;
  UpdateButton: string;
  CategoryHeadingAddPlaylistToSubcategory: string;
  AdminMenuTechnologyLabel: string;
  AdminMenuCategoryLabel: string;
  DeleteButton: string;
  DetailEditNewPageMessage: string;
  DetailEditNewPageButton: string;
  DetailEditExistingPageMessage: string;
  DetailEditExistingPageButton: string;
  NoSearchResults: string;
}

declare module 'CustomLearningAdminWebPartStrings' {
  const strings: ICustomLearningAdminWebPartStrings;
  export = strings;
}
