define([], function() {
  return {
    "WebpartTitleLabel": "Webpart Title (Content Only Mode)",
    "PropertyPaneDescription": "Custom Learning Properties",
    "BasicGroupName": "Default View",
    "WebpartModeLabel": "Select Webpart Mode",
    "WebpartModeDescription": "How you would like to display the webpart",
    "ShowNavigationLabel": "Show Custom Learning Navigation Header",
    "DefaultFilterLabel": "Select a filter",
    "DefaultFilterDescription": "Select a filter to limit the results. You can only filter by one type at a time.",
    "DefaultCategoryLabel": "Filter to Category",
    "DefaultCategoryDescription": "Select a category to limit results.",
    "DefaultSubCategoryLabel": "Filter to Sub-Category",
    "DefaultSubCategoryDescription": "Select a sub-category to limit results.",
    "DefaultPlaylistLabel": "Filter to Playlist",
    "DefaultPlaylistDescription": "Select a category to limit results.",
    "DefaultAssetLabel": "Select an Asset",
    "DefaultAssetDescription": "Select an asset to display from the playlist.",
    "FilterPanelHeader": "Choose the courses that suites you best",
    "FilterPanelAudienceLabel": "I am a",
    "FilterPanelSkillsetLabel": "My skillset is",
    "NavigationHome": "Home",
    "SearchResultItemPlayListLabel": "Playlist: ",
    "SearchResultItemCategoryLabel": "Category: ",
    "SearchPanelPlaceHolderLabel": "Search for Playlists or Assets",
    "LinkPanelCopyLabel": "Copy",
    "HeaderPlaylistPanelCurrentPlaylistLabel": "Current Playlist: ",
    "HeaderPlaylistPanelAdminHeader": "Administration",
    "PlaylistOverviewDesignMessage": "During use this area will show other assets in the playlist it's being shown in.",
    "PlaylistOverviewHeading": "All steps in playlist",
    "BurgerButton": "Burger",
    "LinkButton": "Link",
    "SearchButton": "Search",
    "AdministerPlaylist": "Playlist Administration",
    "NoSearchResults": "No search results matched your query."
  }
});